### ISSUE TITLE
ActionHealth Spamming WorldGuard API Error.

### ISSUE THREAD

**Issue by JustTriinn** [zeshan321/ActionHealth#16]
Hello, AH is spamming a error over and over again about something with worldguard, maybe you can fix it?
[04:46:16 WARN]: [ActionHealth] Task #49 for ActionHealth v3.4.8 generated an exception
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Unknown Source) ~[?:1.8.0_211]
	at com.zeshanaslam.actionhealth.support.WorldGuardAPI.getRegionNames(WorldGuardAPI.java:136) ~[?:?]
	at com.zeshanaslam.actionhealth.utils.HealthUtil.isDisabled(HealthUtil.java:298) ~[?:?]
	at com.zeshanaslam.actionhealth.utils.HealthUtil.matchesRequirements(HealthUtil.java:328) ~[?:?]
	at com.zeshanaslam.actionhealth.LookThread.run(LookThread.java:46) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]

**Comment by zeshan321** [comment]
Thanks for reporting! I'll look into this soon.

**Comment by zeshan321** [comment]
Should be good in 3.5.0.
