### ISSUE TITLE
ActionHealth 1.5.1 - Spigot 1.6.2. Java errors spaming console

### ISSUE THREAD

**Issue by tiradorus** [zeshan321/ActionHealth#21]
Heeyh! :D
Everything is in the title, here is the Java message error:
[11:49:11]: [ERROR] Could not pass event PlayerItemHeldEvent to ActionHealth v3.5.1
java.lang.NullPointerException: null
at com.zeshanaslam.actionhealth.action.ActionHelper.getName(ActionHelper.java:80) ~[?:?]
at com.zeshanaslam.actionhealth.action.ActionHelper.executeTriggers(ActionHelper.java:31) ~[?:?]
at com.zeshanaslam.actionhealth.action.ActionListener.onSwap(ActionListener.java:99) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor525.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.2.jar:git-Paper-189]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.2.jar:git-Paper-189]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.2.jar:git-Paper-189]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.2.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1648) ~[patched_1.16.2.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.PacketPlayInHeldItemSlot.a(SourceFile:30) ~[patched_1.16.2.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.PacketPlayInHeldItemSlot.a(SourceFile:8) ~[patched_1.16.2.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.2.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.2.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.2.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.2.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.2.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.2.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.2.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.2.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.2.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.2.jar:git-Paper-189]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-189]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]

Have a nice day! ;)

**Comment by zeshan321** [comment]
Hey @tiradorus,

ActionHealth cannot support 1.5.1-1.6.2 because action bar does not exist in those versions.

Thanks!
