### ISSUE TITLE
"Show On Look" not working for 1.13.2

### ISSUE THREAD

**Issue by acidicchip** [zeshan321/ActionHealth#3]
Changing "Show On Look" to true in the config.yml and reloading ActionHealth results in the following error:

```
[17:45:49 ERROR]: Fatal error trying to convert ActionHealth v3.2.7:com/zeshanaslam/actionhealth/TargetHelper.class
org.bukkit.plugin.AuthorNagException: No legacy enum constant for LEGACY_IRON_FENCE. Did you forget to define api-version: 1.13 in your plugin.yml?
        at org.bukkit.craftbukkit.v1_13_R2.util.Commodore$1$1.visitFieldInsn(Commodore.java:272) ~[patched_1.13.2.jar:git-Paper-498]
        at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2205) ~[patched_1.13.2.jar:git-Paper-498]
        at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1275) ~[patched_1.13.2.jar:git-Paper-498]
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:679) ~[patched_1.13.2.jar:git-Paper-498]
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:391) ~[patched_1.13.2.jar:git-Paper-498]
        at org.bukkit.craftbukkit.v1_13_R2.util.Commodore.convert(Commodore.java:173) ~[patched_1.13.2.jar:git-Paper-498]
        at org.bukkit.craftbukkit.v1_13_R2.util.CraftMagicNumbers.processClass(CraftMagicNumbers.java:238) ~[patched_1.13.2.jar:git-Paper-498]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.13.2.jar:git-Paper-498]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:192) ~[patched_1.13.2.jar:git-Paper-498]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:95) ~[patched_1.13.2.jar:git-Paper-498]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:84) ~[patched_1.13.2.jar:git-Paper-498]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_191]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_191]
        at com.zeshanaslam.actionhealth.LookThread.run(LookThread.java:40) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-498]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-498]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-498]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

It still works when inflicting damage, however it does not work by looking at them.

Additional Information:
```
[17:48:31 INFO]: This server is running Paper version git-Paper-498 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[17:48:37 INFO]: [WorldEdit] Loading WorldEdit v7.0.0-beta-05;6bbf29b
[17:48:37 INFO]: [WorldGuard] Loading WorldGuard v7.0.0-beta-03;e51a220
```

**Comment by zeshan321** [comment]
Fixed! New build will be up on spigot in a few. :)
