### ISSUE TITLE
JAVA 16 issue

### ISSUE THREAD

**Issue by BillyDas** [zeshan321/ActionHealth#37]
just updated java to java 16, heaps of errors and the plugin no longer works.
Running spigot 1.16.5

```[13:21:49 WARN]: [ActionHealth] Task #22732 for ActionHealth v3.5.3 generated an exception
java.lang.NullPointerException: Cannot invoke "io.lumine.xikage.mythicmobs.api.bukkit.BukkitAPIHelper.isMythicMob(org.bukkit.entity.Entity)" because the return value of "io.lumine.xikage.mythicmobs.MythicMobs.getAPIHelper()" is null
	at com.zeshanaslam.actionhealth.support.MythicMobsSupport.getMythicName(MythicMobsSupport.java:8) ~[?:?]
	at com.zeshanaslam.actionhealth.utils.HealthUtil.isBlacklisted(HealthUtil.java:385) ~[?:?]
	at com.zeshanaslam.actionhealth.LookThread.run(LookThread.java:50) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[server.jar:3096-Spigot-9fb885e-296df56]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[server.jar:3096-Spigot-9fb885e-296df56]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1179) ~[server.jar:3096-Spigot-9fb885e-296df56]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:394) ~[server.jar:3096-Spigot-9fb885e-296df56]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1127) ~[server.jar:3096-Spigot-9fb885e-296df56]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:966) ~[server.jar:3096-Spigot-9fb885e-296df56]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[server.jar:3096-Spigot-9fb885e-296df56]
	at java.lang.Thread.run(Thread.java:831) [?:?]```

```[13:19:34 WARN]: [ActionHealth] Task #108 for ActionHealth v3.5.3 generated an exception
java.lang.NullPointerException: Cannot invoke "io.lumine.xikage.mythicmobs.api.bukkit.BukkitAPIHelper.isMythicMob(org.bukkit.entity.Entity)" because the return value of "io.lumine.xikage.mythicmobs.MythicMobs.getAPIHelper()" is null
	at com.zeshanaslam.actionhealth.support.MythicMobsSupport.getMythicName(MythicMobsSupport.java:8) ~[?:?]
	at com.zeshanaslam.actionhealth.utils.HealthUtil.isBlacklisted(HealthUtil.java:385) ~[?:?]
	at com.zeshanaslam.actionhealth.LookThread.run(LookThread.java:50) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[server.jar:3096-Spigot-9fb885e-296df56]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[server.jar:3096-Spigot-9fb885e-296df56]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1179) ~[server.jar:3096-Spigot-9fb885e-296df56]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:394) ~[server.jar:3096-Spigot-9fb885e-296df56]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1127) ~[server.jar:3096-Spigot-9fb885e-296df56]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:966) ~[server.jar:3096-Spigot-9fb885e-296df56]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[server.jar:3096-Spigot-9fb885e-296df56]
	at java.lang.Thread.run(Thread.java:831) [?:?]```

I think java 16 had some new definitions / syntax changes.

**Comment by zeshan321** [comment]
Doesn't look like its related to Java 16, more like MythicMobs support
