### ISSUE TITLE
[1.14] Broken, not sure what else

### ISSUE THREAD

**Issue by Dragon8oy** [zeshan321/ActionHealth#4]
I updated my server to 1.14 and removed other plugins that may break the game and only left support ones, except ActionHealth.

The health bar doesn't show up and this error loves to popup when someone chats or uses a command:

[11:20:06] [Craft Scheduler Thread - 31/WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_14_R1.PacketPlayOutChat.<init>(net.minecraft.server.v1_14_R1.IChatBaseComponent, byte)              
[11:20:06] [Craft Scheduler Thread - 31/WARN]:  at java.lang.Class.getConstructor0(Class.java:3082)                                                                                                         
[11:20:06] [Craft Scheduler Thread - 31/WARN]:  at java.lang.Class.getConstructor(Class.java:1825)                                                                                                          
[11:20:06] [Craft Scheduler Thread - 31/WARN]:  at com.zeshanaslam.actionhealth.HealthUtil.sendActionBar(HealthUtil.java:187)                                                                               
[11:20:06] [Craft Scheduler Thread - 31/WARN]:  at com.zeshanaslam.actionhealth.HealthUtil.sendHealth(HealthUtil.java:70)                                                                                   
[11:20:06] [Craft Scheduler Thread - 31/WARN]:  at com.zeshanaslam.actionhealth.LookThread.run(LookThread.java:54)                                                                                          
[11:20:06] [Craft Scheduler Thread - 31/WARN]:  at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81)                                                                               
[11:20:06] [Craft Scheduler Thread - 31/WARN]:  at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:51)                                                                     
[11:20:06] [Craft Scheduler Thread - 31/WARN]:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)                                                                          
[11:20:06] [Craft Scheduler Thread - 31/WARN]:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)                                                                          
[11:20:06] [Craft Scheduler Thread - 31/WARN]:  at java.lang.Thread.run(Thread.java:748)

Thanks!
Sorry if this isn't much to go off, I'm just trying to help fix bugs for 1.14

EDIT:

I also get this error when attacking a mob:

[11:51:54] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_14_R1.PacketPlayOutChat.<init>(net.minecraft.server.v1_14_R1.IChatBaseComponent, byte)
[11:51:54] [Server thread/WARN]:        at java.lang.Class.getConstructor0(Class.java:3082)
[11:51:54] [Server thread/WARN]:        at java.lang.Class.getConstructor(Class.java:1825)
[11:51:54] [Server thread/WARN]:        at com.zeshanaslam.actionhealth.HealthUtil.sendActionBar(HealthUtil.java:187)
[11:51:54] [Server thread/WARN]:        at com.zeshanaslam.actionhealth.HealthUtil.sendHealth(HealthUtil.java:70)
[11:51:54] [Server thread/WARN]:        at com.zeshanaslam.actionhealth.HealthListeners.onDamage(HealthListeners.java:112)
[11:51:54] [Server thread/WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:51:54] [Server thread/WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11:51:54] [Server thread/WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:51:54] [Server thread/WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[11:51:54] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316)
[11:51:54] [Server thread/WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[11:51:54] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520)
[11:51:54] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505)
[11:51:54] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:215)
[11:51:54] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:881)
[11:51:54] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:780)
[11:51:54] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:913)
[11:51:54] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.EntityLiving.damageEntity0(EntityLiving.java:1613)
[11:51:54] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.EntityLiving.damageEntity(EntityLiving.java:1067)
[11:51:54] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.EntityHuman.attack(EntityHuman.java:1003)
[11:51:54] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.EntityPlayer.attack(EntityPlayer.java:1511)
[11:51:54] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1889)
[11:51:54] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.PacketPlayInUseEntity.a(SourceFile:69)
[11:51:54] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.PacketPlayInUseEntity.a(SourceFile:13)
[11:51:54] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13)
[11:51:54] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
[11:51:54] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135)
[11:51:54] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[11:51:54] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114)
[11:51:54] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:892)
[11:51:54] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:885)
[11:51:54] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123)
[11:51:54] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:869)
[11:51:54] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:802)
[11:51:54] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by zeshan321** [comment]
Updated. Thanks for the report.
