### ISSUE TITLE
error

### ISSUE THREAD

**Issue by xmakdwerd** [zeshan321/ActionHealth#45]
: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Constructor.newInstance(Object[])" because "fr.mrsheepsheep.tinthealth.THFunctions.border_constructor" is null
[19:21:22 WARN]:        at TintHealth-1.4.7.jar//fr.mrsheepsheep.tinthealth.THFunctions.sendWorldBorderPacket(THFunctions.java:115)
[19:21:22 WARN]:        at TintHealth-1.4.7.jar//fr.mrsheepsheep.tinthealth.THFunctions.setBorder(THFunctions.java:106)
[19:21:22 WARN]:        at TintHealth-1.4.7.jar//fr.mrsheepsheep.tinthealth.THFunctions.sendBorder(THFunctions.java:89)
[19:21:22 WARN]:        at TintHealth-1.4.7.jar//fr.mrsheepsheep.tinthealth.PlayerListener.onDamage(PlayerListener.java:54)
[19:21:22 WARN]:        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
[19:21:22 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[19:21:22 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[19:21:22 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[19:21:22 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:242)[19:21:22 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1116)
[19:21:22 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:996)
[19:21:22 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:951)
[19:21:22 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1148)
[19:21:22 WARN]:        at net.minecraft.world.entity.EntityLiving.damageEntity0(EntityLiving.java:2084)
[19:21:22 WARN]:        at net.minecraft.world.entity.player.EntityHuman.damageEntity0(EntityHuman.java:1059)
[19:21:22 WARN]:        at net.minecraft.world.entity.EntityLiving.damageEntity(EntityLiving.java:1374)
[19:21:22 WARN]:        at net.minecraft.world.entity.player.EntityHuman.damageEntity(EntityHuman.java:966)
[19:21:22 WARN]:        at net.minecraft.server.level.EntityPlayer.damageEntity(EntityPlayer.java:1033)
[19:21:22 WARN]:        at net.minecraft.world.entity.EntityInsentient.attackEntity(EntityInsentient.java:1644)
[19:21:22 WARN]:        at net.minecraft.world.entity.ai.goal.PathfinderGoalMeleeAttack.a(PathfinderGoalMeleeAttack.java:142)
[19:21:22 WARN]:        at net.minecraft.world.entity.ai.goal.PathfinderGoalMeleeAttack.e(PathfinderGoalMeleeAttack.java:134)
[19:21:22 WARN]:        at net.minecraft.world.entity.ai.goal.PathfinderGoalWrapped.e(PathfinderGoalWrapped.java:53)
[19:21:22 WARN]:        at net.minecraft.world.entity.ai.goal.PathfinderGoalSelector.doTick(PathfinderGoalSelector.java:151)
[19:21:22 WARN]:        at net.minecraft.world.entity.EntityInsentient.doTick(EntityInsentient.java:881)
[19:21:22 WARN]:        at net.minecraft.world.entity.EntityLiving.movementTick(EntityLiving.java:3221)
[19:21:22 WARN]:        at net.minecraft.world.entity.EntityInsentient.movementTick(EntityInsentient.java:662)
[19:21:22 WARN]:        at net.minecraft.world.entity.monster.EntityMonster.movementTick(EntityMonster.java:43)
[19:21:22 WARN]:        at net.minecraft.world.entity.EntityLiving.tick(EntityLiving.java:2947)
[19:21:22 WARN]:        at net.minecraft.world.entity.EntityInsentient.tick(EntityInsentient.java:424)
[19:21:22 WARN]:        at net.minecraft.world.entity.monster.EntitySpider.tick(EntitySpider.java:104)
[19:21:22 WARN]:        at net.minecraft.server.level.WorldServer.entityJoinedWorld(WorldServer.java:1186)
[19:21:22 WARN]:        at net.minecraft.world.level.World.a(World.java:1034)
[19:21:22 WARN]:        at net.minecraft.server.level.WorldServer.lambda$tick$7(WorldServer.java:803)
[19:21:22 WARN]:        at net.minecraft.world.level.entity.EntityTickList.a(EntityTickList.java:43)
[19:21:22 WARN]:        at net.minecraft.server.level.WorldServer.doTick(WorldServer.java:784)
[19:21:22 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1629)
[19:21:22 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:492)
[19:21:22 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1480)
[19:21:22 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1270)
[19:21:22 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[19:21:22 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[19:21:22 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Constructor.newInstance(Object[])" because "fr.mrsheepsheep.tinthealth.THFunctions.border_constructor" is null
[19:21:22 WARN]:        at TintHealth-1.4.7.jar//fr.mrsheepsheep.tinthealth.THFunctions.sendWorldBorderPacket(THFunctions.java:115)
[19:21:22 WARN]:        at TintHealth-1.4.7.jar//fr.mrsheepsheep.tinthealth.THFunctions.fadeBorder(THFunctions.java:95)
[19:21:22 WARN]:        at TintHealth-1.4.7.jar//fr.mrsheepsheep.tinthealth.THFunctions.sendBorder(THFunctions.java:90)
[19:21:22 WARN]:        at TintHealth-1.4.7.jar//fr.mrsheepsheep.tinthealth.PlayerListener.onDamage(PlayerListener.java:54)
[19:21:22 WARN]:        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
[19:21:22 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[19:21:22 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[19:21:22 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[19:21:22 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:242)[19:21:22 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1116)
[19:21:22 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:996)
[19:21:22 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:951)
[19:21:22 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1148)
[19:21:22 WARN]:        at net.minecraft.world.entity.EntityLiving.damageEntity0(EntityLiving.java:2084)
[19:21:22 WARN]:        at net.minecraft.world.entity.player.EntityHuman.damageEntity0(EntityHuman.java:1059)
[19:21:22 WARN]:        at net.minecraft.world.entity.EntityLiving.damageEntity(EntityLiving.java:1374)
[19:21:22 WARN]:        at net.minecraft.world.entity.player.EntityHuman.damageEntity(EntityHuman.java:966)
[19:21:22 WARN]:        at net.minecraft.server.level.EntityPlayer.damageEntity(EntityPlayer.java:1033)
[19:21:22 WARN]:        at net.minecraft.world.entity.EntityInsentient.attackEntity(EntityInsentient.java:1644)
[19:21:22 WARN]:        at net.minecraft.world.entity.ai.goal.PathfinderGoalMeleeAttack.a(PathfinderGoalMeleeAttack.java:142)
[19:21:22 WARN]:        at net.minecraft.world.entity.ai.goal.PathfinderGoalMeleeAttack.e(PathfinderGoalMeleeAttack.java:134)
[19:21:22 WARN]:        at net.minecraft.world.entity.ai.goal.PathfinderGoalWrapped.e(PathfinderGoalWrapped.java:53)
[19:21:22 WARN]:        at net.minecraft.world.entity.ai.goal.PathfinderGoalSelector.doTick(PathfinderGoalSelector.java:151)
[19:21:22 WARN]:        at net.minecraft.world.entity.EntityInsentient.doTick(EntityInsentient.java:881)
[19:21:22 WARN]:        at net.minecraft.world.entity.EntityLiving.movementTick(EntityLiving.java:3221)
[19:21:22 WARN]:        at net.minecraft.world.entity.EntityInsentient.movementTick(EntityInsentient.java:662)
[19:21:22 WARN]:        at net.minecraft.world.entity.monster.EntityMonster.movementTick(EntityMonster.java:43)
[19:21:22 WARN]:        at net.minecraft.world.entity.EntityLiving.tick(EntityLiving.java:2947)
[19:21:22 WARN]:        at net.minecraft.world.entity.EntityInsentient.tick(EntityInsentient.java:424)
[19:21:22 WARN]:        at net.minecraft.world.entity.monster.EntitySpider.tick(EntitySpider.java:104)
[19:21:22 WARN]:        at net.minecraft.server.level.WorldServer.entityJoinedWorld(WorldServer.java:1186)
[19:21:22 WARN]:        at net.minecraft.world.level.World.a(World.java:1034)
[19:21:22 WARN]:        at net.minecraft.server.level.WorldServer.lambda$tick$7(WorldServer.java:803)
[19:21:22 WARN]:        at net.minecraft.world.level.entity.EntityTickList.a(EntityTickList.java:43)
[19:21:22 WARN]:        at net.minecraft.server.level.WorldServer.doTick(WorldServer.java:784)
[19:21:22 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1629)
[19:21:22 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:492)
[19:21:22 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1480)
[19:21:22 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1270)
[19:21:22 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[19:21:22 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by zeshan321** [comment]
What version are you using?

**Comment by xmakdwerd** [comment]
1.17.1

**Comment by zeshan321** [comment]
This error is from a plugin called Tinthealth not ActionBarHealth

**Comment by xmakdwerd** [comment]
Here is an ambush, no mistakes, I confused the name: D apparently worked, thanks for the plugin, I really like the simplicity and functionality for disturbing me because of my stupidity

**Comment by zeshan321** [comment]
no problem!
