### ISSUE TITLE
Bug: EntityDamageByEntityEvent 

### ISSUE THREAD

**Issue by madtomic** [zeshan321/ActionHealth#5]
```java
[07:46:55 ERROR]: Could not pass event EntityDamageByEntityEvent to ActionHealth v3.3.1
java.lang.NoClassDefFoundError: com/sk89q/worldguard/WorldGuard
        at com.zeshanaslam.actionhealth.HealthUtil.isDisabled(HealthUtil.java:229) ~[?:?]
        at com.zeshanaslam.actionhealth.HealthListeners.onDamage(HealthListeners.java:28) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor544.execute(Unknown Source) ~[?:?]        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[paper-1.12.2.jar:git-Paper-f59f630b]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[paper-1.12.2.jar:git-Paper-f59f630b]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[paper-1.12.2.jar:git-Paper-f59f630b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[paper-1.12.2.jar:git-Paper-f59f630b]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:94) ~[paper-1.12.2.jar:git-Paper-f59f630b]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:626) ~[paper-1.12.2.jar:git-Paper-f59f630b]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:529) ~[paper-1.12.2.jar:git-Paper-f59f630b]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:658) ~[paper-1.12.2.jar:git-Paper-f59f630b]
        at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity0(EntityLiving.java:1415) ~[paper-1.12.2.jar:git-Paper-f59f630b]
        at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:888) ~[paper-1.12.2.jar:git-Paper-f59f630b]
        at net.minecraft.server.v1_12_R1.EntityMonster.damageEntity(EntityMonster.java:44) ~[paper-1.12.2.jar:git-Paper-f59f630b]
        at net.minecraft.server.v1_12_R1.EntityHuman.attack(EntityHuman.java:1028) ~[paper-1.12.2.jar:git-Paper-f59f630b]
        at net.minecraft.server.v1_12_R1.EntityPlayer.attack(EntityPlayer.java:1406) ~[paper-1.12.2.jar:git-Paper-f59f630b]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1724) ~[paper-1.12.2.jar:git-Paper-f59f630b]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[paper-1.12.2.jar:git-Paper-f59f630b]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[paper-1.12.2.jar:git-Paper-f59f630b]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[paper-1.12.2.jar:git-Paper-f59f630b]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_201]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_201]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[paper-1.12.2.jar:git-Paper-f59f630b]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[paper-1.12.2.jar:git-Paper-f59f630b]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[paper-1.12.2.jar:git-Paper-f59f630b]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[paper-1.12.2.jar:git-Paper-f59f630b]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[paper-1.12.2.jar:git-Paper-f59f630b]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
```

**Comment by zeshan321** [comment]
For WorldGuard 6 and lower (< 1.13 MC version): http://bit.ly/2HXB0ZD

If you are using WG 7, then use the latest version.
