### ISSUE TITLE
Please update to 1.20 because of Error

### ISSUE THREAD

**Issue by SkyKingPX** [zeshan321/ActionHealth#62]
I have errors spamming in the console:

[11:16:00] [Server thread/WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_20_R1.PacketPlayOutChat
[11:16:00] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147)
[11:16:00] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
[11:16:00] [Server thread/WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[11:16:00] [Server thread/WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[11:16:00] [Server thread/WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[11:16:00] [Server thread/WARN]:        at com.zeshanaslam.actionhealth.utils.HealthUtil.sendActionBar(HealthUtil.java:281)
[11:16:00] [Server thread/WARN]:        at com.zeshanaslam.actionhealth.utils.HealthUtil.sendHealth(HealthUtil.java:77)
[11:16:00] [Server thread/WARN]:        at com.zeshanaslam.actionhealth.LookThread.run(LookThread.java:45)
[11:16:00] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:82)
[11:16:00] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415)
[11:16:00] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1257)
[11:16:00] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:388)
[11:16:00] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1198)
[11:16:00] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1015)
[11:16:00] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[11:16:00] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by DUCKONAROLL** [comment]
seconded. probably the best health viewer out there but I can't use it!

**Comment by Strovo** [comment]
third as the best complement says @DUCKONAROLL

**Comment by zeshan321** [comment]
Hey everyone! Sorry for the delay. Can someone test this for me? I currently unable to do that.

[ActionHealth-3.5.9-all.jar.zip](https://github.com/zeshan321/ActionHealth/files/11842949/ActionHealth-3.5.9-all.jar.zip)

**Comment by Strovo** [comment]
![image](https://github.com/zeshan321/ActionHealth/assets/5396543/c660a41f-9991-4907-a0e6-82b54e2dc41d)

![image](https://github.com/zeshan321/ActionHealth/assets/5396543/789f17a3-900e-4fce-9404-418fe4e010c4)

works fine with: Current: git-Purpur-1999 (MC: 1.20.1)*
